// Utility function to map CSV country names to GeoJSON country names
export const createCountryNameMapping = (csvName: string): string => {
  // Map CSV country names to GeoJSON country names
  const nameMapping: { [key: string]: string } = {
    'United States': 'United States of America',
    'Korea, South': 'South Korea',
    'Korea, North': 'North Korea',
    'Czechia': 'Czech Republic',
    'Burma': 'Myanmar',
    'Cote d\'Ivoire': 'Côte d\'Ivoire',
    'Congo, Republic of the': 'Republic of the Congo',
    'Congo, Democratic Republic of the': 'Democratic Republic of the Congo',
    'Bahamas, The': 'The Bahamas',
    'Gambia, The': 'Gambia',
    'Turkey (Turkiye)': 'Turkey',
    'Cabo Verde': 'Cape Verde',
    'Eswatini': 'Swaziland',
    'North Macedonia': 'Macedonia',
    'Bosnia and Herzegovina': 'Bosnia and Herz.',
    'Central African Republic': 'Central African Rep.',
    'Dominican Republic': 'Dominican Rep.',
    'Equatorial Guinea': 'Eq. Guinea',
    'Solomon Islands': 'Solomon Is.',
    'South Sudan': 'S. Sudan',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'United Kingdom': 'United Kingdom',
    'New Zealand': 'New Zealand',
    'Papua New Guinea': 'Papua New Guinea',
    'Saudi Arabia': 'Saudi Arabia',
    'United Arab Emirates': 'United Arab Emirates',
    'Sri Lanka': 'Sri Lanka',
    'Costa Rica': 'Costa Rica',
    'El Salvador': 'El Salvador',
    'New Caledonia': 'New Caledonia',
    'Puerto Rico': 'Puerto Rico',
    'French Polynesia': 'French Polynesia',
    'West Bank': 'West Bank',
    'Gaza Strip': 'Gaza',
    // Additional mappings for the new economic data
    'Russia': 'Russia',
    'China': 'China',
    'India': 'India',
    'Indonesia': 'Indonesia',
    'Nigeria': 'Nigeria',
    'Brazil': 'Brazil',
    'Pakistan': 'Pakistan',
    'Bangladesh': 'Bangladesh',
    'Japan': 'Japan',
    'Mexico': 'Mexico',
    'Vietnam': 'Vietnam',
    'Ethiopia': 'Ethiopia',
    'Philippines': 'Philippines',
    'Germany': 'Germany',
    'Thailand': 'Thailand',
    'Egypt': 'Egypt',
    'Tanzania': 'Tanzania',
    'France': 'France',
    'Iran': 'Iran',
    'South Africa': 'South Africa',
    'Colombia': 'Colombia',
    'Italy': 'Italy',
    'Spain': 'Spain',
    'Kenya': 'Kenya',
    'Uganda': 'Uganda',
    'Canada': 'Canada',
    'Argentina': 'Argentina',
    'Ukraine': 'Ukraine',
    'Peru': 'Peru',
    'Malaysia': 'Malaysia',
    'Poland': 'Poland',
    'Madagascar': 'Madagascar',
    'Angola': 'Angola',
    'Mozambique': 'Mozambique',
    'Australia': 'Australia',
    'Uzbekistan': 'Uzbekistan',
    'Ghana': 'Ghana',
    'Algeria': 'Algeria',
    'Morocco': 'Morocco',
    'Iraq': 'Iraq',
    'Taiwan': 'Taiwan',
    'Venezuela': 'Venezuela',
    'Cameroon': 'Cameroon',
    'Sudan': 'Sudan',
    'Niger': 'Niger',
    'Netherlands': 'Netherlands',
    'Kazakhstan': 'Kazakhstan',
    'Chile': 'Chile',
    'Cambodia': 'Cambodia',
    'Afghanistan': 'Afghanistan',
    'Mali': 'Mali',
    'Ecuador': 'Ecuador',
    'Malawi': 'Malawi',
    'Nepal': 'Nepal',
    'Romania': 'Romania',
    'Yemen': 'Yemen',
    'Guatemala': 'Guatemala',
    'Zambia': 'Zambia',
    'Bolivia': 'Bolivia',
    'Syria': 'Syria',
    'Chad': 'Chad',
    'Burkina Faso': 'Burkina Faso',
    'Benin': 'Benin',
    'Zimbabwe': 'Zimbabwe',
    'Burundi': 'Burundi',
    'Senegal': 'Senegal',
    'Sweden': 'Sweden',
    'Rwanda': 'Rwanda',
    'Portugal': 'Portugal',
    'Belgium': 'Belgium',
    'Haiti': 'Haiti',
    'Switzerland': 'Switzerland',
    'Azerbaijan': 'Azerbaijan',
    'Hungary': 'Hungary',
    'Cuba': 'Cuba',
    'Belarus': 'Belarus',
    'Austria': 'Austria',
    'Israel': 'Israel',
    'Greece': 'Greece',
    'Guinea': 'Guinea',
    'Honduras': 'Honduras',
    'Tunisia': 'Tunisia',
    'Hong Kong': 'Hong Kong S.A.R.',
    'Singapore': 'Singapore',
    'Laos': 'Laos',
    'Paraguay': 'Paraguay',
    'Somalia': 'Somalia',
    'Togo': 'Togo',
    'Nicaragua': 'Nicaragua',
    'Serbia': 'Serbia',
    'Denmark': 'Denmark',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Bulgaria': 'Bulgaria',
    'Jordan': 'Jordan',
    'Norway': 'Norway',
    'Kuwait': 'Kuwait',
    'Finland': 'Finland',
    'Sierra Leone': 'Sierra Leone',
    'Ireland': 'Ireland',
    'Tajikistan': 'Tajikistan',
    'Slovakia': 'Slovakia',
    'Oman': 'Oman',
    'Liberia': 'Liberia',
    'Libya': 'Libya',
    'Turkmenistan': 'Turkmenistan',
    'Panama': 'Panama',
    'Qatar': 'Qatar',
    'Lebanon': 'Lebanon',
    'Georgia': 'Georgia',
    'Uruguay': 'Uruguay',
    'Croatia': 'Croatia',
    'Eritrea': 'Eritrea',
    'Jamaica': 'Jamaica',
    'Lithuania': 'Lithuania',
    'Armenia': 'Armenia',
    'Mongolia': 'Mongolia',
    'Moldova': 'Moldova',
    'Albania': 'Albania',
    'Mauritania': 'Mauritania',
    'Botswana': 'Botswana',
    'Namibia': 'Namibia',
    'Slovenia': 'Slovenia',
    'Latvia': 'Latvia',
    'Bahrain': 'Bahrain',
    'Lesotho': 'Lesotho',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Gabon': 'Gabon',
    'Cyprus': 'Cyprus',
    'Estonia': 'Estonia',
    'Timor-Leste': 'East Timor',
    'Mauritius': 'Mauritius',
    'Kosovo': 'Kosovo',
    'Bhutan': 'Bhutan',
    'Fiji': 'Fiji',
    'Macau': 'Macao S.A.R',
    'Luxembourg': 'Luxembourg',
    'Malta': 'Malta',
    'Guyana': 'Guyana',
    'Comoros': 'Comoros',
    'Maldives': 'Maldives',
    'Djibouti': 'Djibouti',
    'Suriname': 'Suriname',
    'Iceland': 'Iceland',
    'Montenegro': 'Montenegro',
    'Brunei': 'Brunei',
    'Belize': 'Belize',
    'Barbados': 'Barbados',
    'Vanuatu': 'Vanuatu',
    'Saint Lucia': 'Saint Lucia',
    'Samoa': 'Samoa',
    'Grenada': 'Grenada',
    'Saint Vincent and the Grenadines': 'St. Vin. and Gren.',
    'Seychelles': 'Seychelles',
    'Andorra': 'Andorra',
    'Tonga': 'Tonga',
    'Sao Tome and Principe': 'São Tomé and Principe',
    'Palau': 'Palau',
    'Tuvalu': 'Tuvalu',
  };
  
  return nameMapping[csvName] || csvName;
}; 