import React from 'react';
import { FaOilCan, FaFire, FaIndustry, FaSeedling, FaGem, FaCar, FaShip, FaPlane, FaTruck, FaLaptop, FaMobile, FaTshirt, FaAppleAlt, FaGasPump, FaCoffee } from 'react-icons/fa';
import { FaOilWell, FaMicrochip, FaTowerBroadcast, FaGear, FaGears, FaSheetPlastic } from 'react-icons/fa6';
import { LuMilk, LuBeef, LuBean  } from 'react-icons/lu';
import {GiWoodPile, GiWaterRecycling, GiCorn, GiGoldMine, GiMedicines, GiDoubleFish, GiMetalBar, GiBeetleShell, GiTurbine, GiWireCoil, GiBowlOfRice, GiSugarCane, GiSheep, GiButter, GiBeerStein, GiCoconuts, GiBananaBunch, GiPearlNecklace, GiCigarette, GiRubberBoot, GiChemicalDrop, GiOre, GiMinerals, GiStoneBlock, GiShrimp } from "react-icons/gi";
import { BsMinecartLoaded } from "react-icons/bs";
import { MdOilBarrel } from "react-icons/md";
import { TbHexagonLetterR, TbHexagonLetterM, TbHexagonLetterN, TbHexagonLetterC, TbHexagonLetterL, TbHexagonLetterU, TbHexagonLetterZ, TbHexagonLetterI, TbHexagonLetterP, TbPointFilled } from 'react-icons/tb';

interface MapComponentProps {
    searchTerm: string;
    gdpFilter: number;
  }
  

export const iconMap = {
    petroleum: { component: FaOilWell, name: "petroleum", color: "#334155" },
    crude: { component: MdOilBarrel, name: "crude", color: "#334155" },
    condensate: { component: MdOilBarrel, name: "condensate", color: "#475569" },
    oil: { component: FaOilCan, name: "oil", color: "#eab308" },
    gas: { component: FaFire, name: "gas", color: "#52525b" },
    'natural gas': { component: FaFire, name: "natural gas", color: "#52525b" },
    coal: { component: BsMinecartLoaded, name: "coal", color: "#78716c" },
    hydropower: { component: GiWaterRecycling, name: "hydropower", color: "#06b6d4" },
    
    dot: { component: TbPointFilled, name: "dot", color: "#6B7280" },
    
    cars: { component: FaCar, name: "cars", color: "#f87171" },
    iron: { component: TbHexagonLetterI, name: "iron", color: "#6B7280" },
    'iron ore': { component: TbHexagonLetterI, name: "iron ore", color: "#6B7280" },
    steel: { component: FaIndustry, name: "steel", color: "#6B7280" },
    machinery: { component: FaIndustry, name: "machinery", color: "#6B7280" },
    wheat: { component: FaSeedling, name: "wheat", color: "#facc15" },
    grain: { component: FaSeedling, name: "grain", color: "#fde047" },
    gold: { component: GiMetalBar, name: "gold", color: "#facc15" },
    silver: { component: GiMetalBar, name: "silver", color: "#d4d4d4" },
    platinum: { component: GiMetalBar, name: "platinum", color: "#d4d4d4" },
    palladium: { component: GiMetalBar, name: "palladium", color: "#e5e7eb" },
    molybdenum: { component: GiMetalBar, name: "molybdenum", color: "#9ca3af" },
    
    zinc: { component: TbHexagonLetterZ, name: "zinc", color: "#94A3B8" },
    metal: { component: GiGoldMine, name: "metal", color: "#6B7280" },
    minerals: { component: GiGoldMine, name: "minerals", color: "#9CA3AF" },
    diamonds: { component: FaGem, name: "diamonds", color: "#bfdbfe" },
    gems: { component: FaGem, name: "gems", color: "#3B82F6" },
    vehicles: { component: FaCar, name: "vehicles", color: "#EF4444" },
    ships: { component: FaShip, name: "ships", color: "#ef4444" },
    aircraft: { component: FaPlane, name: "aircraft", color: "#fca5a5" },
    transport: { component: FaTruck, name: "transport", color: "#374151" },
    fertilizers: { component: FaSeedling, name: "fertilizers", color: "#4D7C0F" },
    milk: { component: LuMilk, name: "milk", color: "#fdba74" },
    beef: { component: LuBeef, name: "beef", color: "#fdba74" },
    soybeans: { component: LuBean, name: "soybeans", color: "#B5DE8C" },
    soy: { component: LuBean, name: "soy", color: "#B5DE8C" },
    coffee: { component: FaCoffee, name: "coffee", color: "#ca8a04" },

    wood: { component: GiWoodPile, name: "wood", color: "#deb887" },
    timber: { component: GiWoodPile, name: "timber", color: "#deb887" },
    paper: { component: GiWoodPile, name: "paper", color: "#deb887" },
    pulp: { component: GiWoodPile, name: "pulp", color: "#deb887" },

    trucks: { component: FaTruck, name: "trucks", color: "#fb7185" },
    electronics: { component: FaLaptop, name: "electronics", color: "#0d9488" },
    broadcast: { component: FaTowerBroadcast, name: "broadcast", color: "#14b8a6" },
    computers: { component: FaLaptop, name: "computers", color: "#2dd4bf" },
    phones: { component: FaMobile, name: "phones", color: "#2dd4bf" },
    circuits: { component: FaMicrochip, name: "circuits", color: "#14b8a6" },
    parts: { component: FaGears, name: "parts", color: "#f87171" },
    gear: { component: FaGear, name: "gear", color: "#f87171" },
    garments: { component: FaTshirt, name: "garments", color: "#d8b4fe" },
    clothing: { component: FaTshirt, name: "clothing", color: "#d8b4fe" },
    fruits: { component: FaAppleAlt, name: "fruits", color: "#84CC16" },
    corn: { component: GiCorn, name: "corn", color: "#fde047" },
    maize: { component: GiCorn, name: "maize", color: "#fde047" },
    medicine: { component: GiMedicines, name: "medicine", color: "#818cf8" },
    plastics: { component: FaSheetPlastic, name: "plastics", color: "#d8b4fe" },
    fish: { component: GiDoubleFish, name: "fish", color: "#2dd4bf" },
    shellfish: { component: GiBeetleShell, name: "shellfish", color: "#2dd4bf" },
    shrimp: { component: GiShrimp, name: "shrimp", color: "#2dd4bf" },

    REE: { component: TbHexagonLetterR, name: "REE", color: "#fca5a5" },
    'rare earth elements' : { component: TbHexagonLetterR, name: "rare earths", color: "#fca5a5" },
    Mn: { component: TbHexagonLetterM, name: "Mn", color: "#B5DE8C" },
    manganese: { component: TbHexagonLetterM, name: "manganese", color: "#B5DE8C" },
    Ni: { component: TbHexagonLetterN, name: "Ni", color: "#d8b4fe" },
    nickel: { component: TbHexagonLetterN, name: "nickel", color: "#d8b4fe" },
    Cu: { component: TbHexagonLetterC, name: "Cu", color: "#ca8a04" },
    copper: { component: TbHexagonLetterC, name: "copper", color: "#ca8a04" },
    Co: { component: GiMinerals, name: "Co", color: "#a5b4fc" },
    cobalt: { component: GiMinerals, name: "cobalt", color: "#a5b4fc" },
    Li: { component: TbHexagonLetterL, name: "Li", color: "#c7d2fe" },
    lithium: { component: TbHexagonLetterL, name: "lithium", color: "#c7d2fe" },
    nitrates: { component: TbHexagonLetterN, name: "nitrates", color: "#c7d2fe" },
    U: { component: TbHexagonLetterU, name: "U", color: "#fcd34d" },
    uranium: { component: TbHexagonLetterU, name: "uranium", color: "#fcd34d" },
    potash: { component: TbHexagonLetterP, name: "potash", color: "#a16207" },
    lead: { component: TbHexagonLetterL, name: "lead", color: "#6b7280" },
    turbines: { component: GiTurbine, name: "turbines", color: "#60a5fa" },
    wire: { component: GiWireCoil, name: "wire", color: "#fbbf24" },
    electrical: { component: GiWireCoil, name: "electrical", color: "#fbbf24" },
    electricity: { component: GiWireCoil, name: "electricity", color: "#fbbf24" },
    equipment: { component: GiWireCoil, name: "equipment", color: "#fbbf24" },
    appliances: { component: GiWireCoil, name: "appliances", color: "#fbbf24" },
    rice: { component: GiBowlOfRice, name: "rice", color: "#fde68a" },
    sugar: { component: GiSugarCane, name: "sugar", color: "#f9fafb" },
    spice: { component: GiSugarCane, name: "spice", color: "#f9fafb" },
    nuts: { component: GiSugarCane, name: "nuts", color: "#f9fafb" },
    sheep: { component: GiSheep, name: "sheep", color: "#a3e635" },
    butter: { component: GiButter, name: "butter", color: "#fde68a" },
    beer: { component: GiBeerStein, name: "beer", color: "#fbbf24" },
    liquor: { component: GiBeerStein, name: "liquor", color: "#fbbf24" },
    alcohols: { component: GiBeerStein, name: "alcohols", color: "#fbbf24" },
    cocoa: { component: GiCoconuts, name: "cocoa", color: "#a3e635" },
    coconuts: { component: GiCoconuts, name: "coconuts", color: "#a3e635" },
    bananas: { component: GiBananaBunch, name: "bananas", color: "#fde047" },
    jewelry: { component: GiPearlNecklace, name: "jewelry", color: "#f472b6" },
    tobacco: { component: GiCigarette, name: "tobacco", color: "#fbbf24" },
    rubber: { component: GiRubberBoot, name: "rubber", color: "#a3e635" },
    tires: { component: GiRubberBoot, name: "tires", color: "#a3e635" },
    footwear: { component: GiRubberBoot, name: "footwear", color: "#a3e635" },
    chemicals: { component: GiChemicalDrop, name: "chemicals", color: "#818cf8" },
    phosphates: { component: GiChemicalDrop, name: "phosphates", color: "#818cf8" },
    phosphate: { component: GiChemicalDrop, name: "phosphate", color: "#818cf8" },
    acids: { component: GiChemicalDrop, name: "acids", color: "#818cf8" },
    pesticides: { component: GiChemicalDrop, name: "pesticides", color: "#818cf8" },
    nitrogen: { component: GiChemicalDrop, name: "nitrogen", color: "#818cf8" },
    carbonates: { component: GiChemicalDrop, name: "carbonates", color: "#818cf8" },
    ore: { component: GiOre, name: "ore", color: "#6b7280" },
    ores: { component: GiOre, name: "ores", color: "#6b7280" },
    lignite: { component: GiOre, name: "lignite", color: "#6b7280" },
    aluminum: { component: GiOre, name: "aluminum", color: "#6b7280" },
    aluminium: { component: GiMetalBar, name: "aluminium", color: "#6b7280" },
    tin: { component: GiMetalBar, name: "tin", color: "#6b7280" },
    bauxite: { component: GiMetalBar, name: "bauxite", color: "#fdba74" },
    cement: { component: GiOre, name: "cement", color: "#6b7280" },
    //nickel: { component: GiOre, name: "nickel", color: "#6b7280" },
}  